plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
